language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.1.402
before_script:
  - dotnet build
  - dotnet restore
script:  
  - dotnet test ./ShopService.Tests -c Release -f netcoreapp2.1
after_success:
  - sh ./deploy_dockerhub.sh